import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { SharedModule } from '@shared';
import { AlertService, EventDropdownService } from '@core';
import { ProgramsService } from '../../services/programs.service';
import {
  REFERRER_TYPES,
  REFEREE_TYPES,
  RECIPIENT_TYPES,
  REWARD_TYPES,
} from '../../models/program.model';
import type { CreateProgramPayload, Program, ProgramReward } from '../../models/program.model';
import {
  DynamicFormComponent,
  type FormField,
  type DynamicFormSubmitResult,
} from '@shared/components/dynamic-form';

@Component({
  selector: 'app-manage-program',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, SharedModule, DynamicFormComponent],
  templateUrl: './manage-program.component.html',
  styleUrl: './manage-program.component.css',
})
export class ManageProgramComponent implements OnInit {
  isEditMode = false;
  programUuid: string | null = null;
  loading = false;
  loadError = false;
  submitting = false;
  submitError = '';
  validationErrors: Record<string, string[]> = {};

  programForm!: FormGroup;

  readonly referrerTypes = REFERRER_TYPES;
  readonly refereeTypes = REFEREE_TYPES;
  readonly recipientTypes = RECIPIENT_TYPES;
  readonly rewardTypes = REWARD_TYPES;
  readonly Object = Object;
  
  eventsDropdownOptions: { label: string; value: string }[] = [];
  loadingEvents = false;

  // Dynamic Form configurations
  basicInfoFields: FormField[] = [];
  rulesFields: FormField[] = [];
  rewardStageFields: FormField[] = [];
  basicInfoData: Record<string, any> = {};
  rulesData: Record<string, any> = {};

  @ViewChild('basicInfoForm') basicInfoFormComponent!: DynamicFormComponent;
  @ViewChild('rulesForm') rulesFormComponent!: DynamicFormComponent;

  /** Track name/slug for auto-generating slug from name (only in add mode). */
  private lastProgramName = '';
  private lastAutoGeneratedSlug = '';

  get pageTitle(): string {
    return this.isEditMode ? 'Edit Program' : 'Add Program';
  }

  get submitButtonText(): string {
    return this.isEditMode ? 'Update Program' : 'Create Program';
  }

  get rewards(): FormArray {
    return this.programForm.get('rewards') as FormArray;
  }

  get rewardStageOptionsOverrides(): Record<string, { label: string; value: string }[]> {
    return { triggerEvent: this.eventsDropdownOptions };
  }

  constructor(
    private readonly fb: FormBuilder,
    private readonly programsService: ProgramsService,
    private readonly eventDropdownService: EventDropdownService,
    private readonly router: Router,
    private readonly route: ActivatedRoute,
    private readonly alertService: AlertService
  ) {}

  ngOnInit(): void {
    this.initForm();
    this.initFieldConfigurations();
    this.loadEventsDropdown();
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.programUuid = id;
      this.loading = true;
      this.loadProgramData(id);
    }
  }

  private initFieldConfigurations(): void {
    // Basic Information Fields
    this.basicInfoFields = [
      {
        type: 'inputField',
        inputType: 'text',
        label: 'Program Name',
        slug: 'name',
        required: true,
        placeholder: 'e.g. Business To Freelancer',
        colSpan: 1,
      },
      {
        type: 'inputField',
        inputType: 'text',
        label: 'Slug',
        slug: 'slug',
        required: true,
        placeholder: 'e.g. b2f-referral',
        colSpan: 1,
      },
      {
        type: 'textareaField',
        label: 'Description',
        slug: 'description',
        required: true,
        placeholder: 'Describe the program purpose and goals',
        rows: 3,
        colSpan: 2,
      },
      {
        type: 'dropdownField',
        label: 'Referrer Type',
        slug: 'referrerType',
        required: true,
        placeholder: 'Select referrer type',
        options: [...this.referrerTypes],
        colSpan: 1,
      },
      {
        type: 'dropdownField',
        label: 'Referee Type',
        slug: 'refereeType',
        required: true,
        placeholder: 'Select referee type',
        options: [...this.refereeTypes],
        colSpan: 1,
      },
    ];

    // Rules Fields
    this.rulesFields = [
      {
        type: 'inputField',
        inputType: 'number',
        label: 'Attribution Window (days)',
        slug: 'attributionWindowDays',
        required: true,
        placeholder: '30',
        colSpan: 1,
        defaultValue: 30,
        validation: { min: 1 },
      },
      {
        type: 'inputField',
        inputType: 'number',
        label: 'Max Referrals Per User',
        slug: 'maxReferralsPerUser',
        required: true,
        placeholder: '10',
        colSpan: 1,
        defaultValue: 10,
        validation: { min: 1 },
      },
      {
        type: 'inputField',
        inputType: 'number',
        label: 'Cooldown Period (days)',
        slug: 'cooldownPeriodDays',
        required: false,
        placeholder: 'None',
        colSpan: 1,
      },
      {
        type: 'checkboxField',
        label: 'Allow Self Referral',
        slug: 'allowSelfReferral',
        required: false,
        colSpan: 1,
        defaultValue: false,
      },
      {
        type: 'checkboxField',
        label: 'Require Unique Email',
        slug: 'requireUniqueEmail',
        required: false,
        colSpan: 1,
        defaultValue: true,
      },
      {
        type: 'checkboxField',
        label: 'Require Unique Device',
        slug: 'requireUniqueDevice',
        required: false,
        colSpan: 1,
        defaultValue: false,
      },
    ];

    // Reward Stage row fields (one row = one stage)
    this.rewardStageFields = [
      {
        type: 'inputField',
        inputType: 'number',
        label: 'Stage #',
        slug: 'stageNumber',
        required: true,
        colSpan: 1,
        disabled: true,
        validation: { min: 1 },
      },
      {
        type: 'inputField',
        inputType: 'text',
        label: 'Stage Name',
        slug: 'stageName',
        required: true,
        placeholder: 'e.g. Signup Bonus',
        colSpan: 1,
      },
      {
        type: 'dropdownField',
        label: 'Recipient',
        slug: 'recipientType',
        required: true,
        placeholder: 'Select recipient',
        options: [...this.recipientTypes],
        colSpan: 1,
      },
      {
        type: 'dropdownField',
        label: 'Trigger Event',
        slug: 'triggerEvent',
        required: true,
        placeholder: 'Select trigger event',
        options: [], // Filled via optionsOverrides from parent
        colSpan: 1,
      },
      {
        type: 'dropdownField',
        label: 'Type',
        slug: 'rewardType',
        required: true,
        placeholder: 'Select type',
        options: [...this.rewardTypes],
        colSpan: 1,
      },
      {
        type: 'inputField',
        inputType: 'number',
        label: 'Value',
        slug: 'rewardValue',
        required: true,
        placeholder: '0',
        colSpan: 1,
        defaultValue: 0,
        validation: { min: 0 },
      },
    ];
  }

  private initForm(): void {
    this.programForm = this.fb.group({
      rewards: this.fb.array([]),
    });
  }

  private createRewardGroup(reward?: ProgramReward): FormGroup {
    return this.fb.group({
      stageNumber: [{ value: reward?.stageNumber ?? (this.rewards.length + 1), disabled: true }, [Validators.required, Validators.min(1)]],
      stageName: [reward?.stageName ?? '', Validators.required],
      recipientType: [reward?.recipientType ?? 'Referrer', Validators.required],
      triggerEvent: [reward?.triggerEvent ?? null, Validators.required],
      rewardType: [reward?.rewardType ?? 'POINTS', Validators.required],
      rewardValue: [reward?.rewardValue ? Number.parseFloat(reward.rewardValue) : 0, [Validators.required, Validators.min(0)]],
    });
  }

  addReward(): void {
    this.rewards.push(this.createRewardGroup());
  }

  removeReward(index: number): void {
    this.rewards.removeAt(index);
    this.renumberStages();
  }

  private renumberStages(): void {
    this.rewards.controls.forEach((ctrl, i) => {
      ctrl.get('stageNumber')?.setValue(i + 1);
    });
  }

  onBasicInfoValueChanged(values: Record<string, any>): void {
    if (this.isEditMode) return;

    const currentName = (values['name'] ?? '').toString().trim();
    const currentSlug = (values['slug'] ?? '').toString().trim();

    if (currentName === this.lastProgramName) return;

    const userManuallyEdited =
      this.lastAutoGeneratedSlug !== '' &&
      currentSlug !== this.lastAutoGeneratedSlug;

    this.lastProgramName = currentName;

    if (!userManuallyEdited) {
      const newSlug = this.toSlug(currentName);
      this.lastAutoGeneratedSlug = newSlug;

      this.basicInfoFormComponent?.sectionForm
        ?.get('slug')
        ?.setValue(newSlug, { emitEvent: false });
    }
  }

  /** Generate URL-safe slug from program name: lowercase, hyphens for spaces/special chars. */
  private toSlug(displayName: string): string {
    return displayName
      .trim()
      .toLowerCase()
      .replaceAll(/[^a-z0-9\s]/g, '')
      .replaceAll(/\s+/g, '-')
      .replaceAll(/-+/g, '-')
      .replaceAll(/(^-|-$)/g, '');
  }

  private loadEventsDropdown(): void {
    this.loadingEvents = true;
    this.eventDropdownService.getEventsDropdown().subscribe({
      next: (response: any) => {
        this.loadingEvents = false;
        const raw = response?.data;
        const list = Array.isArray(raw) ? raw : raw?.record ?? [];
        if (response?.statusCode === 200 && list.length > 0) {
          this.eventsDropdownOptions = list.map((event: any) => ({
            label: event.displayName ?? event.eventName ?? '',
            value: event.eventName ?? event.displayName ?? ''
          }));
        } else {
          this.eventsDropdownOptions = [];
        }
      },
      error: (error : any) => {
        this.loadingEvents = false;
        // Fallback to empty array if API fails
        this.eventsDropdownOptions = [];
        
        // Show a subtle warning but don't block the form
        if (error.status === 0) {
          this.alertService.showWarningToast('Unable to load events. Please check your connection.');
        } else if (error.status === 500) {
          this.alertService.showWarningToast('Events service temporarily unavailable.');
        }
        // For other errors, silently fallback to manual input
      }
    });
  }

  private loadProgramData(uuid: string): void {
    this.programsService.getById(uuid).subscribe({
      next: (res) => {
        const program = res.data;
        if (!program) {
          this.loadError = true;
          this.loading = false;
          return;
        }
        this.patchForm(program);
        this.loading = false;
      },
      error: (error) => {
        this.loadError = true;
        this.loading = false;
        
        // Provide specific error messages based on error type
        if (error.status === 404) {
          this.alertService.showErrorToast('Program not found. It may have been deleted.');
        } else if (error.status === 403) {
          this.alertService.showErrorToast('You do not have permission to access this program.');
        } else if (error.status === 0) {
          this.alertService.showErrorToast('Network error. Please check your connection.');
        } else if (error.status === 500) {
          this.alertService.showErrorToast('Server error. Please try again later.');
        } else {
          this.alertService.showErrorToast('Failed to load program data. Please try again.');
        }
      },
    });
  }

  goBack(): void {
    this.router.navigate(['/programs']);
  }

  getValidationError(fieldName: string): string | null {
    const errors = this.validationErrors[fieldName];
    return errors && errors.length > 0 ? errors[0] : null;
  }

  hasValidationError(fieldName: string): boolean {
    return !!(this.validationErrors[fieldName] && this.validationErrors[fieldName].length > 0);
  }

  getFriendlyFieldName(fieldName: string): string {
    const fieldMap: Record<string, string> = {
      name: 'Program Name',
      slug: 'Program Slug',
      description: 'Description',
      referrerType: 'Referrer Type',
      refereeType: 'Referee Type',
      'rules.attributionWindowDays': 'Attribution Window',
      'rules.maxReferralsPerUser': 'Max Referrals Per User',
      'rules.cooldownPeriodDays': 'Cooldown Period',
      'rewards.stageName': 'Stage Name',
      'rewards.triggerEvent': 'Trigger Event',
      'rewards.rewardType': 'Reward Type',
      'rewards.rewardValue': 'Reward Value',
    };
    return fieldMap[fieldName] || fieldName;
  }

  private patchForm(program: Program): void {
    // Patch basic info data for dynamic form
    this.basicInfoData = {
      name: program.name || '',
      slug: program.slug || '',
      description: program.description || '',
      referrerType: (program.referrerType || '').toUpperCase(),
      refereeType: (program.refereeType || '').toUpperCase(),
    };

    // Patch rules data for dynamic form
    if (program.programRules) {
      this.rulesData = {
        attributionWindowDays: program.programRules.attributionWindowDays || 30,
        maxReferralsPerUser: program.programRules.maxReferralsPerUser || 10,
        cooldownPeriodDays: program.programRules.cooldownPeriodDays,
        allowSelfReferral: program.programRules.allowSelfReferral || false,
        requireUniqueEmail: program.programRules.requireUniqueEmail !== false,
        requireUniqueDevice: program.programRules.requireUniqueDevice || false,
      };
    }

    // Clear existing rewards
    this.rewards.clear();
    
    // Add rewards if they exist
    if (program.programRewards?.length) {
      program.programRewards.forEach((reward) => {
        this.rewards.push(this.createRewardGroup(reward));
      });
    }
  }

  onBasicInfoSubmit(result: DynamicFormSubmitResult): void {
    // This will be called by the dynamic form, but we'll handle actual submission
    // in the main onSubmit method
  }

  onRulesSubmit(result: DynamicFormSubmitResult): void {
    // This will be called by the dynamic form, but we'll handle actual submission
    // in the main onSubmit method
  }

  private validateFormData(basicInfo: any, rules: any, rewards: any[]): boolean {
    if (!this.validateBasicInfo(basicInfo)) {
      return false;
    }
    
    if (!this.validateRewards(rewards)) {
      return false;
    }
    
    return true;
  }

  private validateBasicInfo(basicInfo: any): boolean {
    if (!basicInfo.name?.trim()) {
      this.submitError = 'Program name is required';
      return false;
    }
    
    if (!basicInfo.slug?.trim()) {
      this.submitError = 'Program slug is required';
      return false;
    }
    
    if (!basicInfo.description?.trim()) {
      this.submitError = 'Program description is required';
      return false;
    }
    
    if (!basicInfo.referrerType) {
      this.submitError = 'Referrer type is required';
      return false;
    }
    
    if (!basicInfo.refereeType) {
      this.submitError = 'Referee type is required';
      return false;
    }
    
    return true;
  }

  private validateRewards(rewards: any[]): boolean {
    if (!rewards || rewards.length === 0) {
      return true;
    }
    
    for (let i = 0; i < rewards.length; i++) {
      const reward = rewards[i];
      if (!reward.stageName?.trim()) {
        this.submitError = `Stage ${i + 1}: Stage name is required`;
        return false;
      }
      if (!reward.triggerEvent?.trim()) {
        this.submitError = `Stage ${i + 1}: Trigger event is required`;
        return false;
      }
      if (reward.rewardValue === null || reward.rewardValue === undefined || reward.rewardValue < 0) {
        this.submitError = `Stage ${i + 1}: Reward value must be 0 or greater`;
        return false;
      }
    }
    
    return true;
  }

  onSubmit(): void {
    if (this.submitting) {
      return;
    }

    // Trigger validation on both dynamic forms
    this.basicInfoFormComponent?.onSubmit();
    this.rulesFormComponent?.onSubmit();

    // Check if dynamic forms are valid
    const basicInfoValid = this.basicInfoFormComponent?.sectionForm?.valid;
    const rulesValid = this.rulesFormComponent?.sectionForm?.valid;
    const rewardsValid = this.programForm.get('rewards')?.valid;

    if (!basicInfoValid || !rulesValid || !rewardsValid) {
      this.submitError = 'Please fill in all required fields correctly';
      return;
    }

    // Clear previous errors
    this.submitError = '';
    this.validationErrors = {};
    
    // Get values from dynamic forms
    const basicInfoValues = this.basicInfoFormComponent.sectionForm.getRawValue();
    const rulesValues = this.rulesFormComponent.sectionForm.getRawValue();
    const rewardsValues = this.rewards.getRawValue();
    
    // Additional validation
    if (!this.validateFormData(basicInfoValues, rulesValues, rewardsValues)) {
      return;
    }
    
    // Prepare the payload
    const payload: CreateProgramPayload = {
      name: basicInfoValues.name,
      description: basicInfoValues.description,
      slug: basicInfoValues.slug,
      referrerType: basicInfoValues.referrerType.toUpperCase(),
      refereeType: basicInfoValues.refereeType.toUpperCase(),
      rules: {
        attributionWindowDays: Number(rulesValues.attributionWindowDays),
        maxReferralsPerUser: Number(rulesValues.maxReferralsPerUser),
        cooldownPeriodDays: rulesValues.cooldownPeriodDays ? Number(rulesValues.cooldownPeriodDays) : null,
        allowSelfReferral: Boolean(rulesValues.allowSelfReferral),
        requireUniqueEmail: Boolean(rulesValues.requireUniqueEmail),
        requireUniqueDevice: Boolean(rulesValues.requireUniqueDevice),
        customRules: {},
      },
      rewards: rewardsValues.map((r: any) => ({
        stageNumber: Number(r.stageNumber),
        stageName: String(r.stageName).trim(),
        recipientType: String(r.recipientType),
        triggerEvent: (r.triggerEvent == null || r.triggerEvent === '') ? '' : String(r.triggerEvent).trim(),
        rewardType: String(r.rewardType),
        rewardValue: String(r.rewardValue),
      })),
    };

    this.submitting = true;

    const request$ = this.isEditMode
      ? this.programsService.update(this.programUuid!, payload)
      : this.programsService.create(payload);

    request$.subscribe({
      next: (response) => {
        this.submitting = false;
        this.submitError = '';
        this.validationErrors = {};
        
        const successMessage = this.isEditMode 
          ? 'Program updated successfully' 
          : 'Program created successfully';
        this.alertService.showSuccessToast(successMessage);
        
        this.router.navigate(['/programs']);
      },
      error: (error) => {
        this.submitting = false;
        console.error('Submit error:', error);
        console.error('Error details:', {
          status: error.status,
          statusText: error.statusText,
          error: error.error,
          message: error.message
        });
        
        if (error.status === 400) {
          if (error.error?.error && typeof error.error.error === 'object') {
            this.validationErrors = error.error.error;
            this.submitError = error.error.message || 'Validation failed';
          } else if (error.error?.message) {
            this.submitError = error.error.message;
          } else {
            this.submitError = 'Invalid data provided. Please check the form.';
          }
          this.alertService.showErrorToast('Validation failed. Please check the form.');
        } else if (error.status === 404) {
          this.submitError = 'Program not found. It may have been deleted.';
          this.alertService.showErrorToast(this.submitError);
        } else if (error.status === 403) {
          this.submitError = 'You do not have permission to perform this action.';
          this.alertService.showErrorToast(this.submitError);
        } else if (error.status === 409) {
          this.submitError = 'A program with this slug already exists.';
          this.alertService.showErrorToast(this.submitError);
        } else if (error.status === 0) {
          this.submitError = 'Network error. Please check your connection.';
          this.alertService.showErrorToast(this.submitError);
        } else if (error.status >= 500) {
          this.submitError = 'Server error. Please try again later.';
          this.alertService.showErrorToast(this.submitError);
        } else {
          this.submitError = `Failed to ${this.isEditMode ? 'update' : 'create'} program. Please try again.`;
          this.validationErrors = {};
          this.alertService.showErrorToast(this.submitError);
        }
      },
    });
  }
}
