import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { SharedModule } from '@shared';
import { AlertService } from '@core';
import { DynamicFormComponent, type FormField } from '@shared/components/dynamic-form';
import { EventsService } from '../../services/events.service';
import type { CreateEventPayload } from '../../models/event.model';

@Component({
  selector: 'app-create-event',
  standalone: true,
  imports: [CommonModule, RouterModule, SharedModule, DynamicFormComponent],
  templateUrl: './create-event.component.html',
  styleUrl: './create-event.component.css',
})
export class CreateEventComponent implements OnInit {
  @ViewChild(DynamicFormComponent) dynamicForm!: DynamicFormComponent;

  submitting = false;
  metadataError = '';
  isEditMode = false;
  eventId: string | null = null;
  initialFormData: Record<string, any> = {};
  loading = false;

  private lastDisplayName = '';
  private lastAutoGeneratedEventName = '';

  readonly eventFormFields: FormField[] = [
     {
      type: 'inputField',
      inputType: 'text',
      slug: 'displayName',
      label: 'Display Name',
      required: true,
      placeholder: 'e.g. User Login',
      colSpan: 1,
    },
    {
      type: 'inputField',
      inputType: 'text',
      slug: 'eventName',
      label: 'Event Name',
      required: true,
      placeholder: 'e.g. user.signup',
      // description: 'Auto-filled from Display Name. Use lowercase with dots (e.g. user.signup, order.placed)',
      colSpan: 1,
    },
    {
      type: 'textareaField',
      slug: 'description',
      label: 'Description',
      required: true,
      placeholder: 'Describe when this event is triggered',
      rows: 3,
      colSpan: 2,
    },
    {
      type: 'checkboxField',
      slug: 'isActive',
      label: 'Active',
      required: false,
      defaultValue: true,
      colSpan: 1,
    },
    {
      type: 'checkboxField',
      slug: 'allowDuplicates',
      label: 'Allow Duplicates',
      required: false,
      defaultValue: false,
      colSpan: 1,
    },
    {
      type: 'dropdownField',
      slug: 'category',
      label: 'Category',
      required: true,
      placeholder: 'Select category',
      options: [
        { label: 'User Action', value: 'user-action' },
        { label: 'System Event', value: 'system-event' },
        { label: 'Transaction', value: 'transaction' },
        { label: 'Notification', value: 'notification' },
        { label: 'Analytics', value: 'analytics' },
        { label: 'Other', value: 'other' },
      ],
      colSpan: 1,
    },
    {
      type: 'textareaField',
      slug: 'expectedMetadataJson',
      label: 'Expected Metadata (JSON)',
      required: false,
      placeholder: '{"userId": "string", "timestamp": "string"}',
      description: 'Key-value pairs as JSON. Values should be type strings (e.g., "string", "number", "boolean"). Example: {"userId": "string", "timestamp": "string"}',
      rows: 4,
      colSpan: 2,
    },
  ];

  constructor(
    private readonly eventsService: EventsService,
    private readonly router: Router,
    private readonly route: ActivatedRoute,
    private readonly alertService: AlertService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe((params) => {
      if (params['id']) {
        this.isEditMode = true;
        this.eventId = params['id'];
        if (this.eventId) {
          this.loadEventData(this.eventId);
        }
      }
    });
  }

  private loadEventData(id: string): void {
    this.loading = true;
    this.eventsService.getById(id).subscribe({
      next: (response) => {
        if (response?.data) {
          const eventData = response.data;
          // Map the event data to form field values
          this.initialFormData = {
            eventName: eventData.eventName || '',
            displayName: eventData.displayName || '',
            description: eventData.description || '',
            category: eventData.category || '',
            isActive: eventData.isActive ?? true,
            allowDuplicates: eventData.allowDuplicates ?? false,
            expectedMetadataJson: eventData.expectedMetadata 
              ? JSON.stringify(eventData.expectedMetadata, null, 2)
              : '',
          };
        }
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading event:', error);
        this.alertService.showError('Failed to load event data');
        this.loading = false;
        this.router.navigate(['/events']);
      },
    });
  }

  onFormValueChanged(values: Record<string, any>): void {
    if (this.isEditMode) return;

    const currentDisplayName = (values['displayName'] ?? '').toString().trim();
    const currentEventName   = (values['eventName']   ?? '').toString().trim();
    // If displayName hasn't changed, nothing to do
    if (currentDisplayName === this.lastDisplayName) return;

    // Detect if the user manually edited eventName (it no longer matches what we auto-generated)
    const userManuallyEdited =
      this.lastAutoGeneratedEventName !== '' &&
      currentEventName !== this.lastAutoGeneratedEventName;

    this.lastDisplayName = currentDisplayName;

    if (!userManuallyEdited) {
      const newEventName = this.toEventName(currentDisplayName);
      this.lastAutoGeneratedEventName = newEventName;

      // Patch only the eventName control without triggering another valueChanges cycle
      this.dynamicForm?.sectionForm
        ?.get('eventName')
        ?.setValue(newEventName, { emitEvent: false });
    }
  }

  private toEventName(displayName: string): string {
    return displayName
      .trim()
      .toLowerCase()
      .replaceAll(/[^a-z0-9\s]/g, '')   // strip special characters
      .replaceAll(/\s+/g, '.');          // spaces → dots
  }

  goBack(): void {
    this.router.navigate(['/events']);
  }

  onFormSubmitted(payload: { values: Record<string, unknown>; isValid: boolean }): void {
    if (!payload.isValid || this.submitting) return;

    const expectedMetadata = this.parseExpectedMetadata(
      payload.values['expectedMetadataJson'] as string | undefined
    );
    if (expectedMetadata === null) {
      this.metadataError = 'Invalid JSON or non-string values in expected metadata.';
      return;
    }
    this.metadataError = '';

    const v = (key: string): string => {
      const value = payload.values[key];
      if (value === null || value === undefined) return '';
      
      // Handle dropdown values that might be objects with 'value' property
      if (typeof value === 'object' && value !== null && 'value' in value) {
        const objValue = (value as { value: unknown }).value;
        if (objValue === null || objValue === undefined) return '';
        if (typeof objValue === 'string') return objValue;
        if (typeof objValue === 'number' || typeof objValue === 'boolean') {
          return String(objValue);
        }
        return '';
      }
      
      // Handle primitive types
      if (typeof value === 'string') return value;
      if (typeof value === 'number' || typeof value === 'boolean') {
        return String(value);
      }
      
      // If it's an object without a 'value' property, return empty string
      // to avoid "[object Object]" stringification
      return '';
    };
    
    const body: CreateEventPayload = {
      eventName: v('eventName') || '',
      displayName: v('displayName') || '',
      description: v('description') || '',
      category: v('category') || '',
      expectedMetadata: expectedMetadata ?? {},
      isActive: Boolean(payload.values['isActive'] ?? true),
      allowDuplicates: Boolean(payload.values['allowDuplicates'] ?? false),
    };

    this.submitting = true;
    
    if (this.isEditMode && this.eventId) {
      // Update existing event
      this.eventsService.update(this.eventId, body).subscribe({
        next: (response) => {
          if (response.statusCode === 200) {
            this.submitting = false;
            this.alertService.showSuccess('Event updated successfully');
            this.router.navigate(['/events']);
          } else {
            this.alertService.showError('Failed to update event');
            this.submitting = false;
          }
        },
        error: (error) => {
          console.error('Error updating event:', error);
          this.submitting = false;
          this.alertService.showError('Failed to update event');
        },
      });
    } else {
      // Create new event
      this.eventsService.create(body).subscribe({
        next: (response) => {
          if (response.statusCode === 200) {
            this.submitting = false;
            this.alertService.showSuccess('Event created successfully');
            this.router.navigate(['/events']);
          } else {
            this.alertService.showError('Failed to create event');
            this.submitting = false;
          }
        },
        error: (error) => {
          console.error('Error creating event:', error);
          this.submitting = false;
          this.alertService.showError('Failed to create event');
        },
      });
    }
  }

  private parseExpectedMetadata(value: string | undefined): Record<string, string> | null {
    if (value == null || String(value).trim() === '') return {};
    try {
      const parsed = JSON.parse(String(value));
      if (typeof parsed !== 'object' || parsed === null) return null;
      const result: Record<string, string> = {};
      for (const [k, v] of Object.entries(parsed)) {
        if (typeof k !== 'string' || typeof v !== 'string') return null;
        result[k] = v;
      }
      return result;
    } catch {
      return null;
    }
  }
}
